# Generated by Django 4.1.5 on 2023-01-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=3)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
