# Generated by Django 4.1.5 on 2023-02-05 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_activation_card_end_date_card_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='relation',
        ),
        migrations.AddField(
            model_name='history',
            name='relation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.card'),
        ),
    ]
