# Generated by Django 4.1.5 on 2023-02-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_card_relation_history_relation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='relation',
        ),
    ]
