# Generated by Django 4.1.5 on 2023-02-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_remove_history_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='series',
            field=models.IntegerField(null=True),
        ),
    ]
