# Generated by Django 4.1.5 on 2023-04-21 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_history_series'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
